services:

  development-application:
    command: npm run dev
    env_file:
      - ./env/development-application.env
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/api/health-check || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s
    image: node:18.12.1
    ports:
      - "3000:3000/tcp"
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./source:/app:rw
    working_dir: /app

  npm:
    entrypoint: npm
    image: node:18.12.1
    stdin_open: true
    tty: true
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./source:/app:rw
    working_dir: /app
