services:

  database:
    env_file:
      - ./database/credentials.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U database -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    image: postgres:18.3
    volumes:
      - pg:/var/lib/postgresql:rw
      - pgdata:/var/lib/postgresql/18/docker:rw

  back-end:
    command: npm run start:debug
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --cacert ./security/certificate-authority-public-certificate.pem --fail https://back-end:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    image: node:24.14.0
    ports:
      - "9229:9229/tcp"
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./back-end:/app:rw
    working_dir: /app

  front-end:
    command: npm run start:dev
    depends_on:
      back-end:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --cacert ./security/certificate-authority-public-certificate.pem --fail https://front-end:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    image: node:24.14.0
    ports:
      - "3000:3000/tcp"
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./front-end:/app:rw
    working_dir: /app

  npm-back-end:
    entrypoint: npm
    image: node:24.14.0
    stdin_open: true
    tty: true
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./back-end:/app:rw
    working_dir: /app

  npm-front-end:
    entrypoint: npm
    image: node:24.14.0
    stdin_open: true
    tty: true
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./front-end:/app:rw
    working_dir: /app

volumes:
  pg:
    name: pg
  pgdata:
    name: pgdata
