services:

  development-database:
    image: mongo:6.0.4
    env_file:
      - ./env/development-database.env
    healthcheck:
      test: ["CMD-SHELL", "mongosh localhost:27017/test --quiet --eval='db.runCommand(\"ping\").ok || failure()' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 5s
    ports:
      - "27017:27017/tcp"
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./database-files:/data/db:rw
      - ./initialize-database:/docker-entrypoint-initdb.d:ro

  development-application:
    command: npm run dev
    depends_on:
      development-database:
        condition: service_healthy
    env_file:
      - ./env/development-application.env
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/api/health-check || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s
    image: node:18.12.1
    ports:
      - "3000:3000/tcp"
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./source:/app:rw
    working_dir: /app

  npm:
    entrypoint: npm
    env_file:
      - ./env/npm.env
    image: node:18.12.1
    stdin_open: true
    tty: true
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./source:/app:rw
    working_dir: /app
