services:

  database:
    env_file:
      - ./environment-variables/database.env
    healthcheck:
      test: ["CMD-SHELL", "mongosh localhost:27017/test --quiet --eval='db.runCommand(\"ping\").ok || failure()' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s
    image: mongo:6.0.4
    ports:
      - "27017:27017/tcp"
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./database/data:/data/db:rw
      - ./database/initialization-scripts:/docker-entrypoint-initdb.d:ro

  development-back-end:
    command: npm run start:dev
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./environment-variables/development-back-end.env
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:7000/app/health-check || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s
    image: node:18.12.1
    ports:
      - "7000:7000/tcp"
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./back-end:/app:rw
    working_dir: /app

  development-front-end:
    command: npm run dev
    depends_on:
      development-back-end:
        condition: service_healthy
    env_file:
      - ./environment-variables/development-front-end.env
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/api/app || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s
    image: node:18.12.1
    init: true
    ports:
      - "3000:3000/tcp"
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./front-end:/app:rw
    working_dir: /app

  npm-auth-micro-service:
    entrypoint: npm
    image: node:18.12.1
    stdin_open: true
    tty: true
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./micro-services/auth:/app:rw
    working_dir: /app

  npm-user-micro-service:
    entrypoint: npm
    image: node:18.12.1
    stdin_open: true
    tty: true
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./micro-services/user:/app:rw
    working_dir: /app

  npm-back-end:
    entrypoint: npm
    image: node:18.12.1
    stdin_open: true
    tty: true
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./back-end:/app:rw
    working_dir: /app

  npm-front-end:
    entrypoint: npm
    env_file:
      - ./environment-variables/npm-front-end.env
    image: node:18.12.1
    stdin_open: true
    tty: true
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./front-end:/app:rw
    working_dir: /app
