services:

  database:
    env_file:
      - ./database/credentials.env
    healthcheck:
      test: ["CMD-SHELL", "mongosh database:27017/test --quiet --eval='db.runCommand(\"ping\").ok' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    image: mongo:7.0.12
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./database/data:/data/db:rw
      - ./database/initialization-scripts:/docker-entrypoint-initdb.d:ro

  back-end:
    command: npm run start:dev
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --cacert ./security/certificate-authority-public-certificate.pem --fail https://back-end:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    image: node:20.15.1
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./back-end:/app:rw
    working_dir: /app

  front-end:
    command: npm run dev
    depends_on:
      back-end:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --cacert ./security/certificate-authority-public-certificate.pem --fail https://front-end:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    image: node:20.15.1
    ports:
      - "3000:3000/tcp"
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./front-end:/app:rw
    working_dir: /app

  npm-back-end:
    entrypoint: npm
    image: node:20.15.1
    stdin_open: true
    tty: true
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./back-end:/app:rw
    working_dir: /app

  npm-front-end:
    entrypoint: npm
    image: node:20.15.1
    stdin_open: true
    tty: true
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./front-end:/app:rw
    working_dir: /app
