services:

  database:
    env_file:
      - ./database/credentials.env
    healthcheck:
      test: ["CMD-SHELL", "mongosh localhost:27017/test --quiet --eval='db.runCommand(\"ping\").ok' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    image: mongo:6.0.5
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./database/data:/data/db:rw
      - ./database/initialization-scripts:/docker-entrypoint-initdb.d:ro

  npm-back-end:
    entrypoint: npm
    image: node:20.2.0
    stdin_open: true
    tty: true
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./back-end:/app:rw
    working_dir: /app
