services:

  development-application:
    build:
      args:
        - GROUP_ID=1000
        - USER_ID=1000
      context: ./images
      dockerfile: development-application.dockerfile
    env_file:
      - ./env/development-application.env
    ports:
      - "3000:3000/tcp"
    volumes:
      - ./source:/app:rw

  npm:
    build:
      args:
        - GROUP_ID=1000
        - USER_ID=1000
      context: ./images
      dockerfile: npm.dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./source:/app:rw
